services:
  backend:
    working_dir: /workspace/backend
    build:
      context: ./backend
      dockerfile: ../.devcontainer/backend/Dockerfile
    volumes:
      - .:/workspace:cached
    ports:
      - "8000:8000"
      - "5678:5678" # Debugger
    command: >
      sh -c "uv run python -m debugpy --listen 0.0.0.0:5678 -m uvicorn src.main:app --host 0.0.0.0 --port 8000 --reload"
    restart: unless-stopped
  
  frontend:
    working_dir: /workspace/frontend
    build:
      context: ./frontend
      dockerfile: ../.devcontainer/frontend/Dockerfile
    user: "bun"
    volumes:
      - .:/workspace:cached
    ports:
      - "5173:5173"
    command: bun run dev
    restart: unless-stopped