services:
  backend:
    build:
      context: ./backend
      dockerfile: ../.devcontainer/backend/Dockerfile
    volumes:
      - .:/workspace:cached
    command: sleep infinity
    restart: "no"
  
  frontend:
    build:
      context: ./frontend
      dockerfile: ../.devcontainer/frontend/Dockerfile
    volumes:
      - .:/workspace:cached
    command: sleep infinity
    restart: "no"